version: '3.8'

services:
  api:
    build:
      context: ./src/trading_agent/api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mlflow
    environment:
      - ENV=production

  mlflow:
    image: mlflow:latest
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlflow/mlruns
    environment:
      - BACKEND_STORE_URI=sqlite:///mlflow.db
      - ARTIFACT_ROOT=/mlflow/artifacts

  airflow:
    image: apache/airflow:2.1.0
    restart: always
    depends_on:
      - api
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=sqlite:////usr/local/airflow/airflow.db
      - AIRFLOW__WEBSERVER__RBAC=True
    volumes:
      - ./airflow/dags:/usr/local/airflow/dags
      - ./airflow/requirements.txt:/requirements.txt
    command: ["bash", "-c", "pip install -r /requirements.txt && airflow db init && airflow webserver & airflow scheduler"]

networks:
  default:
    driver: bridge