apiVersion: v1
kind: Service
metadata:
  name: trading-agent-service
  labels:
    app: trading-agent
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  selector:
    app: trading-agent